const D=window.CATALOGUE;
const $=s=>document.querySelector(s);
const paths={home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1z',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',scan:'M3 8V3h5m8 0h5v5M3 16v5h5m8 0h5v-5M7 7v10m3-10v10m4-10v10m3-10v10',bag:'M5 7h14l1 14H4L5 7Zm4 0V5a3 3 0 0 1 6 0v2',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2',arrow:'M4 12h16m-6-6 6 6-6 6',back:'m14 5-7 7 7 7',pin:'M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 0 1 14 0ZM14 9a2 2 0 1 1-4 0 2 2 0 0 1 4 0',bell:'M5 16h14l-2-4V8a5 5 0 0 0-10 0v4l-2 4Zm5 4h4',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7Z',filter:'M4 6h16M4 12h16M4 18h16M8 3v6m8 0v6M8 15v6',receipt:'M5 3v18l3-2 4 2 4-2 3 2V3l-3 2-4-2-4 2-3-2Zm4 6h6m-6 4h6',leaf:'M20 3C9 2 2 7 5 15s17 3 15-12ZM5 19l10-10'};
const icon=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.spark}"/></svg>`;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>'RM '+(n/100).toFixed(2),pack=p=>(p.size>=1000?p.size/1000:p.size)+(p.size>=1000?(p.unit==='ml'?'L':'kg'):p.unit);
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
let basket=read('pm-basket',{}),alerts=read('pm-alerts',{}),member=read('pm-member',false),stage='splash',slide=0,tab='home',selected=null,value=false,query='',category='All',register=false,receipt=false,username='Guest';
for(const target of [basket,alerts])for(const [k,v] of Object.entries(target)){if(!D.products.some(p=>p.id===k)||!Number.isInteger(v)||v<=0)delete target[k]}
const save=()=>{try{localStorage.setItem('pm-basket',JSON.stringify(basket));localStorage.setItem('pm-alerts',JSON.stringify(alerts));localStorage.setItem('pm-member',JSON.stringify(member));}catch{}};
const product=id=>D.products.find(p=>p.id===id),retailer=id=>D.retailers.find(r=>r.id===id).name,branch=o=>D.branches.find(b=>b.id===o.branch_id),price=o=>member&&o.member_price_sen!==null?o.member_price_sen:o.price_sen;
const eligible=o=>o.available&&new Date(o.valid_until)>new Date(D.as_of)&&(new Date(D.as_of)-new Date(o.observed_at))<=14*86400000&&o.source!=='older_unverified';
const score=o=>price(o)+(value?Math.round(branch(o).distance_km*100):0);
const offers=(id,byValue=false)=>D.offers.filter(o=>o.product_id===id&&eligible(o)).sort((a,b)=>(byValue?score(a):price(a))-(byValue?score(b):price(b)));
const labels={official_partner:'Official / Partner',catalogue:'Retailer catalogue',receipt_verified:'Receipt Verified',community:'Community submitted',older_unverified:'Older / unverified'};
const art=p=>`<div class="product-art" style="background:#${p.color}"><div class="pack"><span class="leaf">♧</span><b>${esc(p.brand.toUpperCase())}</b><small>${esc(pack(p))}</small></div></div>`;
const title=(t,a='')=>`<div class="section"><h2>${t}</h2>${a}</div>`;
function productRow(p){return `<button class="product" data-product="${p.id}">${art(p)}<div class="grow"><div class="tiny muted">${esc(p.brand)}</div><h3>${esc(p.name)}</h3><div class="tiny muted">${esc(p.variant)} · ${pack(p)}</div><div class="from">From ${money(price(offers(p.id)[0]))}</div></div><span class="muted">›</span></button>`}
function nav(){return `<nav class="nav" aria-label="Main navigation">${[['home','home','Home'],['compare','search','Compare'],['scan','scan','Scan'],['list','bag','My list'],['profile','user','Profile']].map(([t,i,l])=>`<button data-tab="${t}" class="${tab===t?'active':''}" aria-label="${l}"><span class="navicon">${icon(i)}</span>${l}</button>`).join('')}</nav>`}
function home(){return `<div class="row between"><div class="row small">${icon('pin')}<b>Petaling Jaya</b><span class="tiny">⌄</span></div><span class="tag soft">DEMO</span></div><div class="tiny muted" style="margin-top:5px">Sample location · not live location</div><h1>Small choices.<br>Bigger savings.</h1><button class="search" data-tab="compare">${icon('search')}<span class="grow">What’s on your shopping list?</span>${icon('filter')}</button><div class="hero"><span class="tag">SHOP SMARTER</span><h2>One product.<br>Every perspective.</h2><p>Price, distance and source.<br>Find the choice that works for you.</p><button class="primary between" data-product="p1">Compare an essential ${icon('arrow')}</button></div>${title('Your daily essentials','<button class="link" data-tab="compare">See all ↗</button>')}${D.products.slice(0,3).map(productRow).join('')}${title('Made for your everyday')}<div class="stats"><div class="card">${icon('bag')}<b>${Object.keys(basket).length} items</b><span class="small muted">In your saved list</span></div><div class="card mint">${icon('bell')}<b>${Object.keys(alerts).length} alerts</b><span class="small muted">Saved on this device</span></div></div><p class="notice">Illustrative prices, sources and distances. No retailer is connected yet. Product illustrations are placeholders.</p>`}
function results(){const rows=D.products.filter(p=>(category==='All'||p.category===category)&&`${p.brand} ${p.name} ${p.variant} ${p.barcode}`.toLowerCase().includes(query.toLowerCase()));return `${title(rows.length+' products')}${rows.length?rows.map(productRow).join(''):'<div class="card empty">No products found.<p class="small muted">Try another brand or a demo barcode.</p></div>'}`}
function comparePage(){return `<h1 style="margin-top:8px">Find your best buy.</h1><p class="small muted">Same product. Real clarity. · Demo prices</p><label class="search">${icon('search')}<input id="search" placeholder="Search milk, MILO, brand…" value="${esc(query)}" aria-label="Search products"></label><div class="chips">${['All',...new Set(D.products.map(p=>p.category))].map(c=>`<button class="chip ${category===c?'active':''}" data-category="${c}">${c}</button>`).join('')}</div><div id="results">${results()}</div>`}
function detail(){const p=product(selected),rows=offers(p.id,true),best=rows[0],b=branch(best);return `<div class="row between"><button class="back" id="back">${icon('back')}Compare</button><button aria-label="Set price alert" id="alert">${icon('bell')}</button></div><div class="row" style="margin-top:24px"><span class="tag">EXACT PRODUCT</span><span class="tag soft">MOCK DATA</span></div><div class="detail-art">${art(p)}</div><h1 style="font-size:27px;margin-bottom:6px">${esc(p.brand)} ${esc(p.name)}</h1><p class="muted" style="margin-top:0">${esc(p.variant)} · ${pack(p)}</p><p class="tiny muted">Matched by demo product identity · ${p.barcode}<br>Brand, variant and pack size are identical.</p><div class="segmented"><button data-rank="cheapest" class="${!value?'active':''}">Cheapest</button><button data-rank="value" class="${value?'active':''}">✧ Best value</button></div><div class="hero price-hero"><span class="tiny" style="color:var(--lime);letter-spacing:1px">${value?'BEST VALUE · DEMO ESTIMATE':'LOWEST ELIGIBLE PRICE'}</span><div class="price">${money(price(best))}</div><div class="small">${esc(retailer(best.retailer_id))} · ${b.distance_km} km away</div><p>${value?`Estimated total ${money(score(best))}: item + return trip at RM 0.50/km. No tolls or parking.`:'Excludes old prices. Member conditions apply only when enabled.'}</p></div><label class="toggle"><input type="checkbox" id="member" ${member?'checked':''}><div><b>Include member prices</b><div class="tiny muted">Demo: assumes you hold each membership</div></div></label>${title(rows.length+' comparable stores')}${rows.map((o,i)=>`<div class="offer ${i===0?'winner':''}"><div class="row between"><h3>${esc(retailer(o.retailer_id))}</h3><span class="amount">${money(price(o))}</span></div><p>${esc(branch(o).name)} · ${branch(o).distance_km} km away</p><p style="color:var(--ink)">${money(price(o)*100/p.size)} / 100${p.unit}${o.member_price_sen!==null?' · Member '+money(o.member_price_sen):''}</p><span class="tag white">Demo · ${labels[o.source]}</span><p class="tiny">Observed 26 Sep 2026 · valid to 3 Oct 2026</p></div>`).join('')}${title('Older / unverified')}${D.offers.filter(o=>o.product_id===p.id&&!eligible(o)).map(o=>`<div class="row between small"><div>${esc(retailer(o.retailer_id))}<p class="tiny muted">1 Aug 2026 · excluded from ranking</p></div><span class="muted">${money(o.price_sen)}</span></div>`).join('')}${title('Price history')}<div class="card small muted">One current demo observation per store. Historical trends need more dated observations.</div><button class="primary" id="add" style="margin-top:24px">+ Add to my list</button><button class="outline" id="alert2" style="margin-top:10px">${alerts[p.id]?'Target saved · '+money(alerts[p.id]):'Set a price alert'}</button>`}
function totals(){return D.branches.map(b=>{let total=0,covered=0;for(const [id,q] of Object.entries(basket)){const o=offers(id).find(o=>o.branch_id===b.id);if(o){covered++;total+=price(o)*q;}}return {b,total,covered}}).filter(x=>x.covered===Object.keys(basket).length&&x.covered>0).sort((a,b)=>a.total-b.total)}
function list(){const ts=totals(),lines=Object.entries(basket),split=lines.reduce((s,[id,q])=>s+price(offers(id)[0])*q,0),stores=new Set(lines.map(([id])=>offers(id)[0].branch_id));return `<h1 style="margin-top:8px">Your everyday list.</h1><p class="small muted">${Object.values(basket).reduce((a,b)=>a+b,0)} items · saved on this device</p>${!lines.length?`<div class="card empty">${icon('bag')}<h3 style="margin-top:16px">Good savings start with a list.</h3><p class="small muted">Find a product and add it here.</p><button class="primary" data-tab="compare">Explore products</button></div>`:lines.map(([id,q])=>`<div class="card" style="margin:12px 0;padding:14px"><button class="product" data-product="${id}" style="padding:0;margin:0">${art(product(id))}<div><h3>${esc(product(id).brand)} ${esc(product(id).name)}</h3><p class="tiny muted">${esc(product(id).variant)} · ${pack(product(id))}</p></div></button><div class="count"><button data-qty="${id},-1" aria-label="Remove one ${esc(product(id).name)}">−</button>${q}<button data-qty="${id},1" aria-label="Add one ${esc(product(id).name)}">+</button></div></div>`).join('')}${lines.length?`${title('One store. One stop.')}${ts.map(t=>`<div class="offer row between"><div><h3>${esc(retailer(t.b.retailer_id))}</h3><p>${esc(t.b.name)} · all items covered</p></div><b>${money(t.total)}</b></div>`).join('')}${title('Smart Split')}<div class="hero price-hero"><span class="tag">LOWEST ITEM TOTAL</span><div class="price">${money(split)}</div><div class="small">${stores.size} stores · before travel costs</div>${lines.map(([id,q])=>`<p>${q} × ${esc(product(id).name)} → ${esc(retailer(offers(id)[0].retailer_id))}</p>`).join('')}<p style="color:var(--lime)">Potential item saving: ${money(ts.length?ts[0].total-split:0)} versus the cheapest complete single-store basket.</p><p>Extra journeys can cost more than you save. This is not route optimisation.</p></div>`:''}`}
function scan(){return `<h1 style="margin-top:8px">Scan. Compare.<br>Shop smarter.</h1><p class="small muted">Demo scanner · camera is not enabled</p><div class="segmented"><button data-scan="barcode" class="${!receipt?'active':''}">Barcode</button><button data-scan="receipt" class="${receipt?'active':''}">Receipt</button></div><div class="scan-frame">${icon(receipt?'receipt':'scan')}${!receipt?'<div class="scan-line"></div>':''}<p>${receipt?'Receipt recognition preview':'Place a barcode inside the frame'}</p><span class="tiny" style="color:#bbd0bd;letter-spacing:1px">SIMULATION · NO CAMERA ACCESS</span></div>${receipt?'<div class="card"><span class="tag">NEXT PHASE</span><h3 style="margin-top:15px">Turn receipts into useful prices.</h3><p class="small muted">Capture → hide personal details → extract items → confirm exact matches → verify.</p><p class="small">OCR and uploads are not connected in this prototype.</p></div>':'<form id="scan-form"><input class="field" id="code" placeholder="DEMO-0001" aria-label="Demo barcode"><p id="scan-error" class="error"></p><button class="primary">Find this product</button></form><button class="outline" id="simulate" style="margin-top:12px">Simulate a successful scan</button><p class="notice">Demo codes are intentionally not real retail barcodes. Production matching will validate GTIN checksums.</p>'}`}
function profile(){return `<h1 style="margin-top:8px">Your space.</h1><div class="card row"><div class="profile-avatar">${icon('user')}</div><div><h2>${esc(username)}</h2><p class="small muted" style="margin:4px 0">Local demo profile</p></div></div><div class="card" style="margin-top:14px"><span class="tiny muted" style="letter-spacing:1px">MONTHLY SAVINGS</span><h2 style="margin-top:12px">No purchases yet</h2><p class="small muted">Savings will use verified purchases and a clearly defined comparison price.</p></div>${title('Your preferences')}<label class="toggle"><input type="checkbox" id="member" ${member?'checked':''}><div><b>Include demo member prices</b><div class="tiny muted">Assumes membership at all sample stores</div></div></label>${title('Price alerts')}${Object.entries(alerts).map(([id,n])=>`<div class="row between checkline"><div><b>${esc(product(id).name)}</b><p class="tiny muted">Target ${money(n)} · no push notifications</p></div><button data-delete-alert="${id}" aria-label="Remove alert">×</button></div>`).join('')||'<p class="small muted">Open a product and set a target price.</p>'}${title('Retailer roadmap')}<p class="small muted">Config-driven · planned, not connected</p><div style="display:flex;flex-wrap:wrap;gap:7px">${D.retailers.map(r=>`<span class="tag soft">${esc(r.name)}</span>`).join('')}</div><button class="outline" id="logout" style="margin-top:26px">Leave demo profile</button><p class="notice">PriceMY 0.1 · English UI · MYR<br>AI, live camera, real accounts and receipt recognition are next-phase integrations. Lists remain on this device.</p>`}
function onboarding(){const titles=['A better price.<br>A smarter everyday.','Same product.<br>A clearer choice.','Your basket.<br>Better together.'],descs=['Compare everyday essentials across Malaysia, in one calm space.','Compare the exact brand, variant and pack size. Know where every price comes from.','Find your best single-store basket, or see what splitting your shop could save.'];return `<div class="entry"><div class="row between"><span class="brand">PriceMY</span><button class="link" id="skip">Skip</button></div><div class="entry-art"><div class="orb">${icon(['bag','search','spark'][slide])}<span class="floating">${['Less searching. More saving.','Exact match ✓','One list. More possibilities.'][slide]}</span></div></div><h1>${titles[slide]}</h1><p>${descs[slide]}</p><div class="dots">${[0,1,2].map(i=>`<i class="${i===slide?'active':''}"></i>`).join('')}</div><button class="primary between" id="next">${slide===2?'Let’s get started':'Continue'}${icon('arrow')}</button></div>`}
function login(){return `<div class="entry"><span class="brand">PriceMY</span><h1 style="margin-top:55px">${register?'Your smarter shop<br>starts here.':'Welcome to<br>better choices.'}</h1><p>Demo mode · no account is created.<br>Use sample details, or explore as a guest.</p><form id="login-form">${register?'<input class="field" name="name" placeholder="Your name" required aria-label="Your name">':''}<input class="field" name="email" type="email" placeholder="Email address" required aria-label="Email address"><input class="field" name="password" type="password" minlength="8" placeholder="Demo password (8+ characters)" required aria-label="Demo password"><button class="primary" style="margin-top:22px">${register?'Create demo profile':'Continue in demo'}</button></form><button class="link" id="guest" style="padding:22px">Explore as guest →</button><button class="link" id="register">${register?'Already have an account? Sign in':'New to PriceMY? Register'}</button><p class="notice center" style="margin-top:30px">Nothing is sent to a server. Lists and alerts stay on this device; login details are not saved.</p></div>`}
function render(keepScroll=false){const top=$('main').scrollTop;$('.nav')?.remove();$('main').innerHTML=stage==='splash'?`<div class="splash"><div class="logo">${icon('bag')}</div><h1>PriceMY</h1><p>Worth every ringgit.</p></div>`:stage==='onboarding'?onboarding():stage==='login'?login():`<div class="page">${selected?detail():({home,compare:comparePage,scan,list,profile}[tab])()}</div>`;if(stage==='app')$('.device').insertAdjacentHTML('beforeend',nav());$('main').scrollTop=keepScroll?top:0;bind();}
function go(t){stage='app';tab=t;selected=null;render();}
function toast(t){$('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.role='status';el.textContent=t;$('.device').append(el);setTimeout(()=>el.remove(),2200)}
function alertDialog(){const dialog=$('dialog');dialog.innerHTML=`<form id="target-form"><h2>Set a price target</h2><p class="small muted">Local demo target. Push notifications are not connected.</p><input class="field" type="number" step="0.01" min="0.01" max="100000" required id="target" placeholder="Target price in RM" aria-label="Target price in RM"><button class="primary">Save target</button><button type="button" class="link" id="cancel" style="width:100%;padding:16px">Cancel</button></form>`;dialog.showModal();$('#cancel').onclick=()=>dialog.close();$('#target-form').onsubmit=e=>{e.preventDefault();alerts[selected]=Math.round(Number($('#target').value)*100);save();dialog.close();render(true);toast('Price target saved on this device')};}
function bind(){document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=()=>go(el.dataset.tab));document.querySelectorAll('[data-product]').forEach(el=>el.onclick=()=>{selected=el.dataset.product;value=false;render()});document.querySelectorAll('[data-category]').forEach(el=>el.onclick=()=>{category=el.dataset.category;render()});document.querySelectorAll('[data-rank]').forEach(el=>el.onclick=()=>{value=el.dataset.rank==='value';render(true)});document.querySelectorAll('[data-scan]').forEach(el=>el.onclick=()=>{receipt=el.dataset.scan==='receipt';render()});document.querySelectorAll('[data-qty]').forEach(el=>el.onclick=()=>{const[id,n]=el.dataset.qty.split(',');basket[id]+=Number(n);if(basket[id]<=0)delete basket[id];save();render(true)});document.querySelectorAll('[data-delete-alert]').forEach(el=>el.onclick=()=>{delete alerts[el.dataset.deleteAlert];save();render(true)});
if($('#search'))$('#search').oninput=e=>{query=e.target.value;$('#results').innerHTML=results();bind()};if($('#back'))$('#back').onclick=()=>{selected=null;render()};if($('#member'))$('#member').onchange=e=>{member=e.target.checked;save();render(true)};
if($('#add'))$('#add').onclick=()=>{basket[selected]=(basket[selected]||0)+1;save();toast('Added to your shopping list')};for(const id of ['alert','alert2'])if($('#'+id))$('#'+id).onclick=alertDialog;
if($('#simulate'))$('#simulate').onclick=()=>{selected='p1';value=false;render()};if($('#scan-form'))$('#scan-form').onsubmit=e=>{e.preventDefault();const p=D.products.find(p=>p.barcode===$('#code').value.trim().toUpperCase());if(p){selected=p.id;render()}else $('#scan-error').textContent='No matching demo code. Try DEMO-0001.'};
const finish=()=>{try{localStorage.setItem('pm-onboarded','true')}catch{}stage='login';render()};if($('#skip'))$('#skip').onclick=finish;if($('#next'))$('#next').onclick=()=>{if(slide<2){slide++;render()}else finish()};if($('#guest'))$('#guest').onclick=()=>{username='Guest';go('home')};if($('#register'))$('#register').onclick=()=>{register=!register;render()};if($('#login-form'))$('#login-form').onsubmit=e=>{e.preventDefault();username=new FormData(e.target).get('name')||'Demo shopper';go('home')};if($('#logout'))$('#logout').onclick=()=>{stage='login';render()};}
render();setTimeout(()=>{stage=read('pm-onboarded',false)?'login':'onboarding';render()},1000);
